<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-E9K3KF14" name="testRunners.TestRunner" tests="5" failures="1" timestamp="8 May 2020 18:58:08 GMT" time="11.250" errors="0">
  <testcase name="feature" time="0.995" classname="testRunners.TestRunner"/>
  <testcase name="feature" time="5.670" classname="testRunners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at stepDefination.DeleteCustomerApiStepDefination.i_should_get_status_code_in_the_response(DeleteCustomerApiStepDefination.java:86)
	at âœ½.I should get status code 200 in the response(./src/test/resources/featureFiles/DeleteCustomerApi.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.672" classname="testRunners.TestRunner"/>
  <testcase name="feature" time="1.272" classname="testRunners.TestRunner"/>
  <testcase name="feature" time="2.641" classname="testRunners.TestRunner"/>
</testsuite> <!-- testRunners.TestRunner -->
